---
- name: Docker install skript
  hosts: docker
  vars:
    some_var: somevar
  tasks:
    - name: Block config
      block:
        - name: Install packages
          apt:
            update_cache: yes
            name: 
              - ca-certificates
              - curl
              - gnupg 
              - lsb-release
        
        - name: Create dir /etc/apt/keyrings
          command: mkdir -m 0755 -p /etc/apt/keyrings

        - name: Download docker key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Execute dpkg command and register output
          shell: dpkg --print-architecture
          register: dpkg_architecture

        - name: Set up the repo
          apt_repository:
            repo: >
              deb [arch={{ dpkg_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.gpg]
              https://download.docker.com/linux/ubuntu
              {{ ansible_distribution_release }} stable
            state: present
            update_cache: yes
            filename: docker
        
        - name: Set chmod on per public key file
          file:
            dest: /etc/apt/keyrings/docker.gpg
            mode: a+x
        
        - name: Install the latest docker version
          apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-buildx-plugin
              - docker-compose-plugin
            update_cache: yes

        - name: docker restart and enable
          systemd:
            name: docker.service
            state: restarted
            enabled: yes

        - name: Add to the Docker group
          user:
            name: shirorng
            groups: docker      

      become: true